### PR TITLE
add more words, sort alphabetically

### PR DESCRIPTION
**Pull request by jzaefferer**
Inspired by https://en.wikipedia.org/wiki/List_of_heavy_metal_bands

Ref #1

### CODE REVIEW

**Comment by Trott** [comment]
Landed in e8b0017f4d73b529d7c0ee5ae71a30de4a45a3f2

Thanks for the contribution! 🎉

**Comment by jzaefferer** [comment]
Thanks for the package!

Could you publish this change on npm?

**Comment by Trott** [comment]
Sure. Version 1.3.0 published.

**Comment by jzaefferer** [comment]
Thanks! If you want to see the result, its in use here: https://github.com/signup-from-bandname/banGen

**Pull request closed without merging**
